# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33d8f9ed4666052378546d935b578b147555263c2210cb89badc35f31180004fb898f33183cdf12c65ac0f640ecc67b42c6624bcd7ebc8230c4e8894de15c414

test:
  secret_key_base: 959fca2cbb2978073933e9da84b577d6f2e45f54aeeae6984dc836187ac02f8f8cd431143714f74d61e879c7a7d2cea7e5e3bee0c6a2d2f73237128c60a80729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
